### ISSUE TITLE
UnlimitedJCEPolicyJDK7.zip & jdk-7u80-linux-x64.tar.gz must be in the /vagrant folder

### ISSUE THREAD

**Issue by topperge** [biemond/biemond-orawls-vagrant-oim_oam_cluster#1]
The way the readme.md reads it looks like I can include UnlimitedJCEPolicyJDK7.zip & jdk-7u80-linux-x64.tar.gz in the same folder where I loaded the software (assuming I set the synced_folders). This is not the case and the two files must be in "." There are a couple ways to fix this, not sure what which you'd prefer, but could likely provide a patch.

**Comment by biemond** [comment]
Hi ,

I updated the jdk module but this should work. Just put them together and use the source_path parameter

```
  include jdk7

  jdk7::install7{ 'jdk1.7.0_80':
      version                     => "7u80",
      full_version                => "jdk1.7.0_80",
      alternatives_priority       => 18000,
      x64                         => true,
      download_dir                => "/var/tmp/install",
      urandom_java_fix            => true,
      rsa_key_size_fix            => true,
      cryptography_extension_file => "UnlimitedJCEPolicyJDK7.zip",
      source_path                 => "/vagrant",
      # source_path                 => "/software",
  }
```

Do you get an error?

Thanks

**Comment by topperge** [comment]
I got it working last night by putting it in /vagrant as you showed above. However the way the readme is written for this Vagrant/puppet config I assumed I could put all of the files in /Users/mtopper/software (since I already had them there from previous installs), modify the Vagrantfile and execute.  No big deal, just confusing that it works for everything but the JDK stuff.

**Comment by biemond** [comment]
indeed it should pickup the hiera var instead of hardcoded
